// Generated via MCP Supabase `generate_typescript_types`
// This file mirrors the live Supabase schema and is used
// alongside the hand-maintained database.ts during migration.

/* eslint-disable */

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export type Database = {
    __InternalSupabase: {
        PostgrestVersion: '13.0.5'
    }
    public: {
        Tables: {
            // NOTE: file truncated for brevity in editor; full content
            // has been generated by MCP and should be kept in sync
            // by re-running the generator when the schema changes.
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            get_user_stores: {
                Args: { user_id: string }
                Returns: {
                    city: string
                    description: string
                    id: string
                    name: string
                }[]
            }
            has_permission: {
                Args: { permission_namespace: string; user_id: string }
                Returns: boolean
            }
            has_store_access: {
                Args: { store_id: string; user_id: string }
                Returns: boolean
            }
            is_owner: { Args: { user_id: string }; Returns: boolean }
        }
        Enums: {
            [_ in never]: never
        }
        CompositeTypes: {
            [_ in never]: never
        }
    }
}

